from datetime import timedelta
from typing import List, Dict, Protocol
from reasoning.environment.IncidentStore import IncidentStore


class BusAllocatorProtocol(Protocol):
    def allocate_relevant_trips(self, time_threshold: timedelta) -> None: ...
    def allocate_buses(self, trip_ids: List[int]) -> None: ...
    def send_log(self, msg: str) -> None: ...
    async def wait_for_agents(self) -> None: ...
    def get_incident_store(self) -> IncidentStore: ...
    def get_system_status(self) -> Dict[str, int]: ...